### ISSUE TITLE
Custom enchantments

### ISSUE THREAD

**Issue by Caaruzo** [jacky8399/PortableBeacons#3]
Hi there,

great addon. But i need to ask something. How can i add custom enchantments like nightvision and fireresistance?

Thx much.

**Comment by Caaruzo** [comment]
I wanted to add nightvision with an aqua_affinity book and tried this in custom-enchantments section of the config file. But it wont work.

 night_vision:
    enabled: true
    name: '&dNachtsicht {level}'
    enchantment: aqua_affinity
    owner-usage-only: false

**Comment by jacky8399** [comment]
Custom recipes have been added to v1.13. Add the following recipe to `recipes.yml`, or just use `/pb recipe create ...` while holding an Aqua Affinity book.
```yaml
night_vision:
  type: smithing
  input: minecraft:enchanted_book{StoredEnchantments:[{id:aqua_affinity,lvl:1}]}
  input-amount: 1
  modifications:
    add:
      minecraft:night_vision: 1
  exp-cost: 0
```
